### ISSUE TITLE
cannot import name 'notf' from 'tensorboard.compat'

### ISSUE THREAD

**Issue by GorMorGor** [dvschultz/stylegan2-ada-pytorch#36]
**Everything was running just fine for the past 3 months but since today I'm keep running this issue.**

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 582, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 575, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 422, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/content/drive/My Drive/colab-sg2-ada-pytorch/stylegan2-ada-pytorch/training/training_loop.py", line 244, in training_loop
    stats_tfevents = tensorboard.SummaryWriter(run_dir)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 220, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 251, in _get_file_writer
    self.flush_secs, self.filename_suffix)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py", line 61, in __init__
    log_dir, max_queue, flush_secs, filename_suffix)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 47, in <module>
    from tensorflow._api.v2.compat.v1 import lite
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/__init__.py", line 9, in <module>
    from . import experimental
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.py", line 8, in <module>
    from . import authoring
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.py", line 8, in <module>
    from tensorflow.lite.python.authoring.authoring import compatible
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/authoring/authoring.py", line 43, in <module>
    from tensorflow.lite.python import convert
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert.py", line 29, in <module>
    from tensorflow.lite.python import util
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/util.py", line 51, in <module>
    from jax import xla_computation as _xla_computation
  File "/usr/local/lib/python3.7/dist-packages/jax/__init__.py", line 59, in <module>
    from .core import eval_context as ensure_compile_time_eval
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 47, in <module>
    import jax._src.pretty_printer as pp
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 56, in <module>
    CAN_USE_COLOR = _can_use_color()
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/pretty_printer.py", line 54, in _can_use_color
    return sys.stdout.isatty()
AttributeError: 'Logger' object has no attribute 'isatty'

**Comment by redyellowRain** [comment]
Hello @GorMorGor - i'm having the same issue but I'm using the notebook through Google colab. Would you know how to fix this issue in Colab?

**Comment by GorMorGor** [comment]
@redyellowRain Thank you. I'm using Colab, too. The workaround with the file replacement I have described in the comment above helps me run the process in Colab, but I would like to know how to make this replacement automatic and fix it in the code.

**Comment by redyellowRain** [comment]
@GorMorGor - I see. i tried your solution and it works. even removing the init file completely with os.remove() works . I'll be waiting for a better solution as well but as a work around it's good and i thank you for that!

**Comment by zuuukiiio** [comment]
Hello @GorMorGor, I encounter the exact same problem, but by deleting the __init__.py file, it gave me a new cannot import name 'tf' error. Any idea?

**Comment by GorMorGor** [comment]
@zuuukiiio I belief this is a separate issue caused by PyTorch, Tensorflow or one of the modules mismatch. I have no idea what versions you have installed and, most importantly, what versions it should be.
For Google Colab initial issue with init.py arose after update to Python 3.7 from Python 3.6. Consider downgrading this first.
