### ISSUE TITLE
Unable to generate single images after training with the notebook

### ISSUE THREAD

**Issue by chasetyoung** [dvschultz/stylegan2-ada-pytorch#44]
Unable to generate single images after training with the notebook.

After training a model, the notebook is unable to generate image results. When the following command is run, the following error occurs-
!python generate.py --outdir=/content/out/images/ --trunc=0.8 --seeds=0 --network=/content/drive/MyDrive/ladiescrop-network-snapshot-012885.pkl

generate.py:59: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif(len(seeds) is not 3):
Traceback (most recent call last):
  File "generate.py", line 25, in <module>
    from opensimplex import OpenSimplex
  File "/usr/local/lib/python3.8/dist-packages/opensimplex/__init__.py", line 4, in <module>
    from .api import *
  File "/usr/local/lib/python3.8/dist-packages/opensimplex/api.py", line 2, in <module>
    from .internals import _init, _noise2, _noise3, _noise4, _noise2a, _noise3a, _noise4a
  File "/usr/local/lib/python3.8/dist-packages/opensimplex/internals.py", line 9, in <module>
    from numba import njit, prange
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

**Comment by daanrongen** [comment]
I'm having the same problem. It seems like an issue with the `opensimplex` import

**Comment by daanrongen** [comment]
So the issue is within the interpolation logic to generate video outputs (interpolating from seed to seed). `opensimplex` is used in the `OSN()` class that is used to predict noise in a `noiseloop`. If you comment all these out (along with the `if else` logic from `generate_images()`, it works. But you'll only be able to use `interpolation=linear` in `generate.py`.
